# Generated by Django 4.2.5 on 2023-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='pizza/img/pizza-error-404.jpg', upload_to='pizza/img'),
        ),
    ]
